%YAML:1.0
#Camera choice: 1 for built-in webcam, 1 for usb webcam
CAMERA_N: 1
#chess board Width and Height
BOARD_W: 8
BOARD_H: 6
#Board size in MM and PX
BOARD_WIDTH_PX: 110
BOARD_HEIGHT_PX: 75
WIDTH_WINDOW: 640
HEIGHT_WINDOW: 480
DIS_X_CAM_CR: 10
DIS_Y_CAM_CR: 145
#HSV color filter tolerance
HSV_TOLERANCE1: 50
HSV_TOLERANCE2: 40
HSV_TOLERANCE3: 40
#Bary point filter tolerance en mm for CDs
TOLERANCE_MIN_CD: 60
TOLERANCE_MAX_CD: 100
#Bary point filter tolerance en mm for lingots
TOLERANCE_MIN_LINGOT: 40
TOLERANCE_MAX_LINGOT: 90
#cv::Point Trans(TRANS_X-config.DIS_X_CAM_CR, TRANS_Y+config.DIS_Y_CAM_CR);
TRANS_X: -150
TRANS_Y: 430
