# Compilateur
CC=g++

# Libs
# !!! il faut absolument mettre -lpthread !!!
LIBS=comManager.o -lpthread 

# To compile all ^^
LIST=sample
all : $(LIST)

#
sample : sample.cpp
	$(CC) -o sample sample.cpp $(LIBS)

# To delete tmp files
clean : 


