CPP = g++

OPTS =  -I"irrlicht-1.7.2/include" -I"/usr/X11R6/include" -L"/usr/X11R6/lib" -L"irrlicht-1.7.2/lib/Linux" -lIrrlicht -lGL -lGLU -lXxf86vm -lXext -lX11

all:	$(CPP) main.cpp -o template $(OPTS)

clean:	rm template


